### ISSUE TITLE
Incorporation into bin3C.

### ISSUE THREAD

**Issue by cerebis** [dyxstat/HiCzin#2]
I am the author of bin3C and just quickly read through your bioRxiv paper just now. It's exciting to read about new normalisation methods applied to metagenomic Hi-C. I would be interested in testing the effectiveness of HiCzin in bin3C, but I am concerned about the computational requirements. In the figures of the manuscript, is it made clear anywhere the difference in performance between the TAXAassign version and the unlabelled? I think overall an unlabelled approach will probably be a lot easier for end users and novel environments.

Do you happen to have any of the intermediate data files at hand? Such as a normalised contact map and the related contigs?

**Comment by dyxstat** [comment]
Hi Matthew,

Thanks for your interest in our new paper. I will soon update our contig
fasta file and will notify you then. The Hi-C contact information can be
obtained from https://github.com/dyxstat/HiCzin/tree/main/data

If you have any questions, welcome to ask me.

Best,
Yuxuan Du

**Comment by dyxstat** [comment]
Hi,

Thanks for your interest in our new paper. The performance of the unlabeled version can be seen in the supplementary material.

I will soon update the contig fasta file and will notify you then. The Hi-C contact information can be obtained from https://github.com/dyxstat/HiCzin/tree/main/data

**Comment by cerebis** [comment]
I realised after I created the issue that you've put some data in the
subfolder.

I'm having a go with HiCzin it on a metagenomic assembly I am currently
working on, using the unlabelled mode. Only problem is that it fails with
the following error as soon as it starts the actual normalisation. Does
this mean that glmmTMB has failed to find a good fit?

normalizing
Model convergence problem; non-positive-definite Hessian matrix. See
vignette('troubleshooting')
skip
Error: object 'fit1' not found
In addition: There were 50 or more warnings (use warnings() to see the
first 50)
Execution halted

**Comment by dyxstat** [comment]
Hi,

There are a lot of potential reasons for the non-positive-definite Hessian matrix in the optimization step for glmmTMB. One possible reason is that zero-inflation is estimated to be near zero (a strongly negative zero-inflation parameter).

Could you try the negative binomial mode (-n) and see how the results are? From our experience, the results of these two modes don't differ to a large extent. 

BTW, I suggest installing the source version of 'glmmTMB' by **install.packages("glmmTMB", type="source")**
in case of another error derived from the package version (https://github.com/glmmTMB/glmmTMB/issues/615):
'Error in .Call("FreeADFunObject", ptr, PACKAGE = DLL) : "FreeADFunObject" not available for .Call() for package "glmmTMB"'.

Thanks

**Comment by cerebis** [comment]
Ok thanks very much. I had a look to see what the authors of glmmTMB said
about that error message.

I'm also wondering if I am just not filtering the data sufficiently. In
unlabelled mode, the assumption is that spurious contacts are rare, however
the counting procedure in bin3C doesn't try to eliminate invalid pairs by
any means besides low quality alignments. Many tools (often in human work)
go much further and drop pairs which are spaced too closely together.
Imposing such a minimum on pair separation isn't as simple for fragmented
metagenomic assemblies.

Do you clean up the contacts or are they pretty raw? I saw in the paper
that you're using the same flag filter in samtools as I do.

**Comment by cerebis** [comment]
I should be clear that I mention bin3C only because I am extracting raw
contacts from its intermediate state file (contact_map.p.gz)

**Comment by dyxstat** [comment]
In my opinion, it is very challenging to do similar clean-up like Hi-C data of humans. Actually, for the data preprocessing, I followed the pipelines of both bin3C and another paper MetaTOR, and didn't discard raw Hi-C read pairs other than the samtools filtering, alignment quality, and matches.
